config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'event_calenders#index'

  get '/about', to: 'users#about'

  resources  :users, only: [:index, :show, :edit, :update]

  resources :events do
    resources :event_comments, only: [:create, :destroy]
  end

  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :event_calenders

  resources :notifications, only: :index
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_one_attached :t_image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :tweet, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  def create_notification_like(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and tweet_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_tweet_comment(current_user, tweet_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = TweetComment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).where.not(user_id: user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_tweet_comment(current_user, tweet_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_tweet_comment(current_user, tweet_comment_id, user_id)
  end

  def save_notification_tweet_comment(current_user, tweet_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      tweet_id: id,
      tweet_comment_id: tweet_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :non_active_user
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @tweets = Tweet.page(params[:page]).per(25).order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path, notice: "ツイートの投稿が完了しました。"
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet), notice: "ツイートの更新を完了しました。"
    else
      render :edit
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path, notice: "ツイートの投稿を削除しました。"
  end

  private
  def tweet_params
    params.require(:tweet).permit(:tweet, :t_image)
  end

  def ensure_correct_user
    @tweet = Tweet.find(params[:id])
    if user_signed_in? && @tweet.user.id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to tweets_path
    end
  end

  def non_active_user
    unless user_signed_in? && current_user.active?
      flash[:notice] = "アカウントがアクティブではありません。会長または副会長に連絡してください。"
      redirect_to '/'
    end
  end
end

app/views/tweets/edit.html.erb
<div class="container"> 
  <div class="row">
    <%= render 'shared/tweet_error_messages' %>
    
    <div class="tweet-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">ツイート</h2>
      </div>

      <div class="form-body">
        <%= form_for @tweet do |f| %>

          <div class="field">
            <%= f.text_area :tweet, autofocus: true, placeholder: "つぶやき", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :t_image, "ツイート画像：" %>
            <%= f.file_field :t_image %>
          </div>

          <div class="field">
            <%= f.submit "更新", class: "btn btn-lg btn-block btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">  
  <%= render 'shared/flash_notice' %>
  <div class="row text-center">

    <div class="tweet-index w-100">

      <% if user_signed_in? && current_user.active? %>
        <%= link_to 'ツイート', new_tweet_path, class: "btn btn-sm btn-outline-success mr-auto ml-auto" %>
      <% end %>

      <table class="table table-hover mt-4 mb-4">
        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td class="w-25 pl-0 pr-0">
                <% if tweet.user.p_image.attached? %>
                  <%= image_tag tweet.user.p_image %>
                <% else %>
                  <%= image_tag 'big.jpg' %>
                <% end %>
                <span class="tweet-name">
                  <%= link_to tweet.user.nickname, user_path(tweet.user) %>
                </span>
              </td>
              <td class="text-left">

                <%= link_to tweet.tweet, tweet_path(tweet) %>

                <div class="tweet-date text-right de-flex justify-content-between mt-1">

                  
                  <% if tweet.t_image.attached? %>
                    <%= image_tag tweet.t_image %>
                  <% end %>

                  <i class="far fa-comment-dots mr-1"></i><%= tweet.tweet_comments.count %>
                  <% if tweet.favorited_by?(current_user) %>
                    <%= link_to tweet_favorites_path(tweet), method: :delete do %>
                      <i class="fa fa-heart ml-1" aria-hidden="true" style="color: red;"></i>
                      <%= tweet.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to tweet_favorites_path(tweet), method: :post do %>
                      <i class="fa fa-heart-o ml-1" aria-hidden="true"></i>
                      <%= tweet.favorites.count %>
                    <% end %>
                  <% end %>
                  <i class="far fa-clock ml-1"></i> <%= tweet.created_at.strftime('%Y/%m/%d/%R') %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
      </table>

    </div>

    <div class="kaminari mt-4">
      <%= paginate @tweets, window: 2 %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">  
  <div class="row">
    <%= render 'shared/tweet_error_messages' %>
    
    <div class="tweet-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">ツイート</h2>
      </div>

      <div class="form-body">
    
        <%= form_for @tweet do |f| %>

          <div class="field">
            <%= f.text_area :tweet, autofocus: true, placeholder: "いまどうしてる？", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :t_image, "ツイート画像：" %>
            <%= f.file_field :t_image %>
          </div>

          <div class="field">
            <%= f.submit "投稿", class: "btn btn-lg btn-block btn-success" %>
          </div>

        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/tweets/show.html.erb
<div class="container">  
  <%= render 'shared/flash_notice' %>
  <div class="row">
    <%= render 'shared/tweet_error_messages' %>

    <div class="w-100 text-center mb-4">
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <%= link_to '編集', edit_tweet_path, class: "btn btn-sm btn-outline-success mr-2" %>
        <%= link_to '削除', tweet_path, class: "btn btn-sm btn-outline-success", method: :delete,"data-confirm" => "本当に消しますか？" %>
      <% end %>
    </div>

    <div class="tweet-index mb-4 w-100 has-shadow-1 bg-white p-4">
      <div class="tweet-content mb-4">

        <%= safe_join(@tweet.tweet.split("\n"), tag(:br)) %>

        <% if @tweet.t_image.attached? %>
          <hr>
          <div class="tweet-image text-center">
            <%= image_tag @tweet.t_image %>
          </div>
          <hr>
        <% end %>

        <div class="text-right">
          <i class="far fa-clock mr-1 ml-1"></i><%= @tweet.created_at.strftime('%Y/%m/%d/%R') %>
        </div>
      </div>

      <div class="tweet-user d-flex justify-content-between align-items-center">

        <% if @tweet.favorited_by?(current_user) %>
          <li>
            <%= link_to tweet_favorites_path(@tweet), method: :delete, class: "btn btn-sm" do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= @tweet.favorites.count %> いいね
            <% end %>

            <% if @tweet.favorites.present? %>
              <a class="btn btn-sm" data-toggle="collapse" href="#collapse" role="button" aria-expanded="false" aria-controls="collapse">
                表示
              </a>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to tweet_favorites_path(@tweet), method: :post, class: "btn btn-sm" do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= @tweet.favorites.count %> いいね
            <% end %>

            <% if @tweet.favorites.present? %>
              <a class="btn btn-sm" data-toggle="collapse" href="#collapse" role="button" aria-expanded="false" aria-controls="collapse">
                表示
              </a>
            <% end %>
          </li>
        <% end %>

        <%= link_to(user_path(@tweet.user)) do %>
          <% if @tweet.user.p_image.attached? %>
            <%= image_tag @tweet.user.p_image %>
          <% else %>
            <%= image_tag 'big.jpg' %>
          <% end %>
          <%= @tweet.user.nickname %>
        <% end %>

      </div>



      <table class="table table-hover mt-4 mb-0 collapse" id="collapse">
      <tbody class="favorite">
        <% @tweet.favorites.each do |favorite| %>
          <% if favorite.user.active? && favorite.user.nickname.present? %>
          <tr>
            <td>      
              <% if favorite.user.p_image.attached? %>
                <%= image_tag favorite.user.p_image %>
              <% else %>
                <%= image_tag 'big.jpg' %>
              <% end %>
            </td>
            <td><%=link_to favorite.user.nickname, user_path(favorite.user) %></td>
            <td>いいね！しました。</td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    </div>

    <div class="comment-section text-center w-100">

      <div class="comment-count">
        <%= "【コメント：#{@tweet.tweet_comments.count}件】" %>
      </div>

      <div class="comment-content">
        <% @tweet.tweet_comments.each do |tweet_comment| %>
          <div class="comment">
          <hr>
            <div class="comment-body">
              <div class="comment-top d-flex flex-row align-items-center mb-2">
                <div class="comment-avatar mr-3">
                  <div class="avatar">
                    <% if tweet_comment.user.p_image.attached? %>
                      <%= image_tag tweet_comment.user.p_image %>
                    <% else %>
                      <%= image_tag 'big.jpg' %>
                    <% end %>
                  </div>
                </div>
                <div class="comment-nickname">
                  <%= link_to tweet_comment.user.nickname, user_path(tweet_comment.user) %>
                </div>
              </div>
              <div class="commnt-bottom">
                <div class="comment-text d-flex flex-row align-items-center mb-2">
                  <i class="far fa-comment-dots mr-3 ml-3"></i>
                  <span class="text-left"><%= safe_join(tweet_comment.comment.split("\n"), tag(:br)) %></span>
                </div>
                <div class="comment-date d-flex flex-row align-items-center">
                  <i class="far fa-clock mr-3 ml-3"></i>
                  <%= tweet_comment.created_at.strftime('%Y/%m/%d/%R') %>
                  <% if user_signed_in? && current_user.id == tweet_comment.user_id %>
                    <%= link_to "削除", tweet_tweet_comment_path(tweet_comment.tweet.id, tweet_comment.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "delete ml-auto mr-2 btn btn-sm btn-success" %> 
                  <% end %>
                </div>
              </div>
            </div>
            
          </div>
          
        <% end %>
        <hr>
      </div>

    </div>



    <% if user_signed_in? && current_user.active? %>
      <div class="comment-form text-center w-100">
        <div class="mb-2">【コメントフォーム】</div>
          <%= form_for [@tweet, @tweet_comment] do |f| %>
            <div class="d-flex">
              <%= f.text_area :comment, placeholder: "コメントをここに", class: "text-area flex-grow-1 mr-2" %>
              <%= f.submit "送信する", class: "btn btn-success mb-2" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>