config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'event_calenders#index'

  get '/about', to: 'users#about'

  resources  :users, only: [:index, :show, :edit, :update]

  resources :events do
    resources :event_comments, only: [:create, :destroy]
  end

  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :event_calenders

  resources :notifications, only: :index
end

app/models/event_calender.rb
class EventCalender < ApplicationRecord

  validates :title, presence: true, length: { maximum: 12 }
  validates :content, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :start_time, presence: true
end

app/controllers/event_calenders_controller.rb
class EventCalendersController < ApplicationController

  before_action :ensure_correct_user, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @event_calenders = EventCalender.all
  end

  def new
    @event_calender = EventCalender.new
  end

  def show
    @event_calender = EventCalender.find(params[:id])
  end

  def create
    @event_calender = EventCalender.new(event_calender_parameter)
    if @event_calender.save
      redirect_to event_calender_path(@event_calender), notice: "活動の投稿を完了しました。"
    else
      render :new
    end
  end

  def destroy
    @event_calender = EventCalender.find(params[:id])
    @event_calender.destroy
    redirect_to event_calenders_path, notice:"活動を削除しました"
  end

  def edit
    @event_calender = EventCalender.find(params[:id])
  end

  def update
    @event_calender = EventCalender.find(params[:id])
    if @event_calender.update(event_calender_parameter)
      redirect_to event_calender_path(@event_calender), notice: "活動を編集しました"
    else
      render 'edit'
    end
  end

  private

  def event_calender_parameter
    params.require(:event_calender).permit(:title, :content, :start_time)
  end

  def ensure_correct_user
    unless user_signed_in? && current_user.executive?
      flash[:notice] = "権限がありません"
      redirect_to '/'
    end
  end

end

app/views/event_calenders/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/event_calender_error_messages' %>

    <div class="event_calender-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">活動編集</h2>
      </div>

      <div class="form-body">
        <%= form_with(model: @event_calender, local: true) do |form| %>

          <div class="field">
            <%= form.text_field :title, placeholder: "タイトル", class: "form-control" %>
          </div>

            <div class="field">
            <%= form.date_field :start_time, placeholder: "日時", class: "form-control" %>
          </div>

          <div class="field">
            <%= form.text_area :content, placeholder: "内容", class: "form-control" %>
          </div>


          <div class="field">
            <%= form.submit "更新", class: "btn btn-lg btn-block btn-dark" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/event_calenders/index.html.erb
<div class="container">
  <%= render 'shared/flash_notice' %>
  <div class="row">

<!-- コロナお知らせ

    <div class="attention alert alert-danger text-center">
      <div class="attention-section">
        <h1>コロナウイルス感染拡大に伴うお知らせ </h1>
        <p class="attention-text">
          この度Teeでは、緊急事態宣言の延長を受け、<br>
          5月に予定していた新歓の活動を全て中止します。<br>
          新歓を楽しみにされていた新入生、新規の方々<br>
          大変申し訳ありません。
        </p>
        <div class="sinkan">
          <div class="bg-white">
            <p class="attention-text text-center">
              <h4 class="pt-2">※ 5月活動中止</h4>
               新歓開催日<br>
              5/10(日) 14:00~ ❌<br>
              5/17(日) 14:00~ ❌<br>
            </p>
          </div>

          <h5>その代わり</h5>

          <i class="fas fa-angle-double-down mb-2"></i>
          <i class="fas fa-angle-double-down mb-2"></i>
          <i class="fas fa-angle-double-down mb-2"></i>
          
          <div class="bg-white yotei">
            <h4 class="mt-2">※ Teeインスタライブ</h4>
            <p class="text-center mb-0">
              5/17(日) 15:00~<br>
              5/22(日) 22:00~
            </p>

            <a href="https://www.instagram.com/tee_0106/" target="_blank" class="flowbtn12 insta_btn2 w-50 mt-1 mb-2">
              <i class="fab fa-instagram"></i><span>Instagram</span>
            </a>

            <p class="fz-12">
              Teeのインスタアカウントでライブ配信します！<br>
              インスタライブでは、質問をもらって<br>
              それに答えていく形で<br>
              新入生にTeeの紹介をします！！<br>
              是非、参加お待ちしております！！！
            </p>
          </div>
        </div>
      </div>
    </div>

  コロナお知らせ -->

    <div class="main mb-4">
      <%= image_tag 'top.jpg' %>
      <div class="caption text-center">
        <h1>関西インカレサークルTee</h1>
        <p>毎月6日と18日と第4金曜に活動中！<br>
        当サークルは学生のみで構成しており、<br>
        近畿圏のいろんな大学の学生がいます！！<br>
        新入生に限らずまだサークルに入れてない<br>
        っていう2,3回生も募集してますよ～！</p>
        <%= link_to "詳細はこちら", about_path, class: "btn btn-light " %>
      </div>
    </div>

    <div class="embed-responsive embed-responsive-16by9 movie">
      <iframe class="embed-responsive-item" src="https://drive.google.com/file/d/1b4u3eiYC95HwN-OSi3EcvBnJSNHGdgiL/preview"></iframe>
      <div class="movie-title">
        <h4 class="text-center">
          2020年度<br>
          サークル紹介
        </h4>
      </div>
    </div>

    <div class="small mx-auto mt-1">
      再生されない場合は、右上の↗︎マークを押してください。
    </div>

    <div class="cta w-100 text-center my-4">
      <%= link_to 'ログイン', new_user_session_path, class: "btn login-btn" %>
      <%= link_to 'サインアップ', new_user_registration_path, class: "btn sign-up-btn" %>
    </div>

    <div class="text-center w-100">
      <p> 
        <i class="fas fa-angle-double-up"></i>　Teeのメンバーの方は　<i class="fas fa-angle-double-up"></i><br>
        ログインまたはサインアップしてください<br>
        <br>
        まだ所属してない方はこちら<br>
        <i class="fas fa-angle-double-down"></i>
      </p>
    </div>

    <div class="cta w-100 text-center mb-4">
      <%= link_to 'Teeについて', about_path, class: "btn about-btn" %>
      <%= link_to '活動紹介', events_path, class: "btn event-btn" %>
    </div>

    <div class="calender-index w-100">

      <div class="w-100 text-center">
        <% if user_signed_in? && current_user.executive? %>
          <%= link_to '投稿', new_event_calender_path, class: "mx-auto btn btn-sm btn-outline-dark mb-2" %>
        <% end %>
      </div>


      <%= month_calendar events: @event_calenders do |date, event_calenders| %>
        <%= date.day %>

        <% event_calenders.each do |event_calender| %>
          <div>
            <%= link_to(event_calender_path(event_calender)) do %>
              <%= image_tag 'big.jpg' %>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <div class="calender-description d-flex align-items-center px-4 mb-4 justify-content-center">
        <%= image_tag 'big.jpg', class: "calender-img"%>
        <span>：マークをタップすると活動の詳細が確認できます</span>
      </div>

    </div>

    <div class=" text-center w-100">
      <p>
        何か聞きたいことや相談がある方は<br>
        DMやLine@などで気軽にご連絡下さい。<br>
        <i class="fas fa-angle-double-down"></i>
      </p>
    </div>

    <ul class="snsbtniti2 w-100 d-flex mb-0 justify-content-between">
      <li>
        <a  href="https://twitter.com/tee_01060106" target="_blank" class="flowbtn12 fl_tw2">
          <i class="fab fa-twitter"></i><span>Twitter</span>
        </a>
      </li>
      <li>
        <a href="https://www.instagram.com/tee_0106/" target="_blank" class="flowbtn12 insta_btn2">
          <i class="fab fa-instagram"></i><span>Instagram</span>
        </a>
      </li>
      <li>
        <a href="https://lin.ee/pAVUUIS" target="_blank" class="flowbtn12 fl_li2">
          <i class="fab fa-line"></i><span>LINE＠🙋‍♂️</span>
        </a>
      </li>  
      <li>
        <a href="https://lin.ee/m67IgK5" target="_blank" class="flowbtn12 fl_li2">
          <i class="fab fa-line"></i><span>LINE＠🙋‍♀️</span>
        </a>
      </li>
    </ul>

  </div>
</div>

app/views/event_calenders/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/event_calender_error_messages' %>

    <div class="event_calender-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">活動投稿</h2>
      </div>

      <div class="form-body">
        <%= form_with(model: @event_calender, local: true) do |form| %>

          <div class="field">
            <%= form.text_field :title, placeholder: "タイトル", class: "form-control" %>
          </div>

            <div class="field">
            <%= form.date_field :start_time, placeholder: "日時", class: "form-control" %>
          </div>

          <div class="field">
            <%= form.text_area :content, placeholder: "内容", class: "form-control" %>
          </div>


          <div class="field">
            <%= form.submit "投稿", class: "btn btn-lg btn-block btn-dark" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/event_calenders/show.html.erb
<div class="container">
  <%= render 'shared/flash_notice' %>
  <div class="row">
    <div class="w-100 text-center mb-4">
      <% if user_signed_in? && current_user.executive? %>
        <%= link_to '編集', edit_event_calender_path, class: "btn btn-sm btn-outline-dark mr-2" %>
        <%= link_to '削除', event_calender_path, class: "btn btn-sm btn-outline-dark", method: :delete,"data-confirm" => "本当に消しますか？" %>
      <% end %>
    </div>

    <div class="calender-show mb-4 w-100 text-center has-shadow-1">
      <h3 class="event-title mb-0">
        <%= @event_calender.title %>
      </h3>

      <hr>
      
      <div class="event-content">
        <p>【活動内容】</p>
        <p class="text-left"><%= safe_join(@event_calender.content.split("\n"), tag(:br)) %></p>
      </div>
    </div>

  </div>
</div>