config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'event_calenders#index'

  get '/about', to: 'users#about'

  resources  :users, only: [:index, :show, :edit, :update]

  resources :events do
    resources :event_comments, only: [:create, :destroy]
  end

  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :event_calenders

  resources :notifications, only: :index
end

app/views/shared/_event_calender_error_messages.erb
<% if @event_calender.errors.any? %>
  <div id="error_explanation" class="alert alert-danger w-100 mb-0" role="alert">
    <h4><%= pluralize(@event_calender.errors.count, "") %>つのエラーがあります。</h4>
    <ul class="pl-4">
    <% @event_calender.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_error_messages.erb
<% if @event.errors.any? %>
  <div id="error_explanation" class="alert alert-danger w-100 mb-0" role="alert">
    <h4><%= pluralize(@event.errors.count, "") %>つのエラーがあります。</h4>
    <ul class="pl-4">
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_notice.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key} alert alert-success") %>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer text-center bg-light p-4 border-top border-bottom w-100">
    © 2020 created by Gaito
  </div>

app/views/shared/_header.html.erb
<div class="header">
    <nav class="bg-light navbar navbar-expand-lg fixed-top pt-2 pb-2 border-top border-bottom">
      <a class="navbar-brand logo" href="/">
        <%= image_tag 'big.jpg', class: "header-logo" %>
      </a>
      <div class="heade-title">
        <h3 class="mb-0">Tee Official Site</h3>
      </div>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon tu-ti-toggle">
          <i class="fas fa-bars"></i>
          <% if user_signed_in? && current_user.active? %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle notification-circle"></i>
            <% end %>
          <% end %>
        </span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item d-flex justify-content-between align-items-center">
            <%= link_to 'Teeについて', about_path, class: "nav-link" %>
            <% if user_signed_in? %>
              <%= link_to(user_path(current_user)) do %>
                <% if current_user.p_image.attached? %>
                  <%= image_tag current_user.p_image, class: "nav-link navbar-toggler" %>
                <% else %>
                  <%= image_tag 'big.jpg', class: "nav-link navbar-toggler" %>
                <% end %>
              <% end %>
            <% end %>
          </li>
          <li class="nav-item d-flex justify-content-between align-items-center">
            <%= link_to '活動紹介', events_path, class: "nav-link" %>
            <% if user_signed_in? %>
              <%= link_to current_user.name, user_path(current_user), class: "nav-link navbar-toggler" %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item d-flex justify-content-between align-items-center">
              <%= link_to 'メンバー', users_path, class: "nav-link" %>
              <%= link_to current_user.college, user_path(current_user), class: "nav-link navbar-toggler" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ツイート', tweets_path, class: "nav-link" %>
            </li>
            <% if current_user.active? %>
              <li class="nav-item tu-ti">
                <%= link_to '通知', notifications_path, class: "nav-link"  %>
                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle notification-circle"></i>
                <% end %>
              </li>
            <% end %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to '管理者ページ', '/admin', class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            <li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

app/views/shared/_tweet_error_messages.erb
<% if @tweet.errors.any? %>
  <div id="error_explanation" class="alert alert-danger w-100 mb-0" role="alert">
    <h4><%= pluralize(@tweet.errors.count, "") %>つのエラーがあります。</h4>
    <ul class="pl-4">
    <% @tweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_error_messages.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger w-100 mb-0" role="alert">
    <h4><%= pluralize(@user.errors.count, "") %>つのエラーがあります。</h4>
    <ul class="pl-4">
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>