config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'event_calenders#index'

  get '/about', to: 'users#about'

  resources  :users, only: [:index, :show, :edit, :update]

  resources :events do
    resources :event_comments, only: [:create, :destroy]
  end

  resources :tweets do
    resources :tweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :event_calenders

  resources :notifications, only: :index
end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :e_image
  has_many :event_comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 12 }
  validates :content, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :date, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :ensure_correct_user, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.with_attached_e_image.order(date: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path, notice: "活動の投稿を完了しました。"
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event), notice: "活動の更新を完了しました。"
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to events_path, notice: "活動の投稿を削除しました。"
  end

  private
  def event_params
    params.require(:event).permit(:title, :date, :content, :e_image)
  end

  def ensure_correct_user
    unless user_signed_in? && current_user.executive?
      flash[:notice] = "権限がありません"
      redirect_to events_path
    end
  end
end

app/views/events/edit.html.erb
<div class="container">  
  <div class="row">
    <%= render 'shared/event_error_messages' %>

    <div class="event-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">活動編集</h2>
      </div>
      <div class="form-body">
        <%= form_for @event do |f| %>

          <div class="field">
            <%= f.text_field :title, autofocus: true, placeholder: "タイトル", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.date_field :date, autofocus: true, placeholder: "日時", class: "form-control"%>
          </div>

          <div class="field">
            <%= f.text_area :content, autofocus: true, placeholder: "内容", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :e_image, "集合写真：" %>
            <%= f.file_field :e_image %>
          </div>

          <div class="field">
          <%= f.submit "更新", class: "btn btn-lg btn-block btn-warning" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">  
  <%= render 'shared/flash_notice' %>
  <div class="row">

      <% if user_signed_in? && current_user.executive? %>
        <%= link_to '投稿', new_event_path, class: "btn btn-sm btn-outline-warning mr-auto ml-auto" %>
      <% end %>

    <div class="event-index mt-4 w-100">
      <% @events.each do |event| %>
        <div class="mb-4 event-box">
          <div class="event-index-btn">
            <a class="btn btn-warning btn-lg btn-block d-flex justify-content-between align-items-center" data-toggle="collapse" href="#collapseExample<%= event.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
              <%= event.title %>
              <span class="event-head">
                <%= event.date %>
              </span>
            </a>
          </div>
          <div class="collapse acd-content mt-2 text-center has-shadow-1" id="collapseExample<%= event.id %>">
            <div>
              <% if event.e_image.attached? %>
                <%= image_tag event.e_image %>
              <% end %>
            </div>
            <div class="d-flex align-items-center mt-2">
              <%= link_to "活動詳細", event_path(event), class: "btn btn-sm col-6 btn-outline-warning tc-5" %>
              <div class="col-6 text-center"><%= "コメント#{event.event_comments.count}件" %></div>
            </div>
          </div>
          
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container"> 
  <div class="row">
    <%= render 'shared/event_error_messages' %>
    
    <div class="event-new has-shadow-1 w-100 mt-4">
      <div class="form-header text-center pt-4 pb-4">
        <h2 class="mb-0">活動投稿</h2>
      </div>
      <div class="form-body">
        <%= form_for @event do |f| %>

          <div class="field">
            <%= f.text_field :title, autofocus: true, placeholder: "タイトル", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.date_field :date, autofocus: true, placeholder: "日時", class: "form-control"%>
          </div>

          <div class="field">
            <%= f.text_area :content, autofocus: true, placeholder: "内容", class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :e_image, "集合写真：" %>
            <%= f.file_field :e_image %>
          </div>

          <div class="field">
          <%= f.submit "投稿", class: "btn btn-lg btn-block btn-warning" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <%= render 'shared/flash_notice' %>
  <div class="row">

    <div class="w-100 text-center mb-4">
      <% if user_signed_in? && current_user.executive? %>
        <%= link_to '編集', edit_event_path, class: "btn btn-sm btn-outline-warning mr-2" %>
        <%= link_to '削除', event_path, class: "btn btn-sm btn-outline-warning", method: :delete,"data-confirm" => "本当に消しますか？" %>
      <% end %>
    </div>

    <div class="acd-content mb-4 w-100 text-center has-shadow-1">
      <h5 class="event-title mb-0">
        <%= @event.title %>
      </h5>
      <div class="event-head d-flex align-items-center mt-2 justify-content-end">
        <span class="event-date mr-2">
          <%= @event.date %>
        </span>
      </div>

      <hr>

      <div class="event-image text-center">
        <% if @event.e_image.attached? %>
          <%= image_tag @event.e_image %>
        <% end %>
      </div>
 
      <hr>
      
      <div class="event-content">
        <p>【活動内容】</p>
        <p class="text-left"><%= safe_join(@event.content.split("\n"), tag(:br)) %></p>
      </div>
    </div>

    <div class="comment-section text-center w-100">

      <div class="comment-count">
        <%= "【コメント：#{@event.event_comments.count}件】" %>
      </div>

      <div class="comment-content">
        <% @event.event_comments.each do |event_comment| %>
          <div class="comment">
          <hr>
            <div class="comment-body">
              <div class="comment-top d-flex flex-row align-items-center mb-2">
                <div class="comment-avatar mr-3">
                  <div class="avatar">
                    <% if event_comment.user.p_image.attached? %>
                      <%= image_tag event_comment.user.p_image %>
                    <% else %>
                      <%= image_tag 'big.jpg' %>
                    <% end %>
                  </div>
                </div>
                <div class="comment-nickname">
                  <%= link_to event_comment.user.nickname, user_path(event_comment.user) %>
                </div>
              </div>
              <div class="commnt-bottom">
                <div class="comment-text d-flex flex-row align-items-center mb-2">
                  <i class="far fa-comment-dots mr-3 ml-3"></i>
                  <span class="text-left"><%= safe_join(event_comment.comment.split("\n"), tag(:br)) %></span>
                </div>
                <div class="comment-date d-flex flex-row align-items-center">
                  <i class="far fa-clock mr-3 ml-3"></i>
                  <%= event_comment.created_at.strftime('%Y/%m/%d/%R') %>
                  <% if user_signed_in? && current_user.id == event_comment.user_id %>
                    <%= link_to "削除", event_event_comment_path(event_comment.event.id, event_comment.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "delete ml-auto mr-2 btn btn-sm btn-warning" %> 
                  <% end %>
                </div>
              </div>
            </div>
            
          </div>
          
        <% end %>
        <hr>
      </div>
    </div>

    <% if user_signed_in? && current_user.active? %>
      <div class="comment-form text-center w-100">
        <div class="mb-2">【コメントフォーム】</div>
          <%= form_for [@event, @event_comment] do |f| %>
            <div class="d-flex">
              <%= f.text_area :comment, placeholder: "コメントをここに", class: "text-area flex-grow-1 mr-2" %>
              <%= f.submit "送信する", class: "btn btn-warning mb-2" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>